### PR TITLE
Mapper updates

### PR DESCRIPTION
**Pull request by phantomastray**
@aryaKetan @jagadeesh-huliyar  Please review the changes.
This shall enable defining mappings as
```json
		{
			"destinationNamespace":"or_test",
			"destinationEntity":"PersonGenericMapped",
			"columnMap": {
				"id":"id",
				"firstName":"name[].first",
				"lastName":"name[].last",
				"birthDate":"date.birth",
				"deleted":"deleted",
				"source_event_date" : "date.source.event[]",
				"birthDate":"date.source.event[]"
			},
			"groupNo":"1"
		}]

```

### CODE REVIEW

**Comment by aryaKetan** [comment]
a) @phantomastray  Can you re-check-in after removing the formatting changes. If  we need to re-format,lets do it in a separate check-in

Also @jagadeesh-huliyar wanted to discuss the changes before merging the change. I was not able to entirely explain your use-case. Can you setup some time to discuss this today, post that we will take necessary steps.

**Comment by phantomastray** [comment]
@aryaKetan @jagadeesh-huliyar  Sure. I'll come over at 4pm to discuss the changes.

**Comment by phantomastray** [comment]
@jagadeesh-huliyar @aryaKetan 
I've updated the pull request. (removed formatting changes)

**Comment by jagadeesh-huliyar** [comment]
@aryaKetan - Please review and accept the pull request.

Thanks and Regards
Jagadeesh

**Comment by aryaKetan** [comment]
Seems ok . @phantomastray @pratyay-banerjee , the getEventColumnMapping method has become too complex for a good review and lacks good method level comments.

Can you guys break down the big method into smaller method and have appropriate documentation.

Also @phantomastray  , have you tested that normal config ( without [] ) works fine .

**Comment by aryaKetan** [comment]
@phantomastray @pratyay-banerjee : Update on this??

**Comment by pratyay-banerjee** [comment]
@phantomastray  Lets meet tomorrow and discuss what changes can be done to make the method modular. 
The current logic  in getEventColumnMapping()  is the extension of the previous getDestinationEventColumnMapping() I had written, so off the top I can say the function can be made smaller by calling 3 sub methods each for the 3 cases of not nested, nested map only and nested map-list.

**Comment by phantomastray** [comment]
@pratyay-banerjee - I've added method level comments as discussed.
Let's meet tomorrow.

**Comment by phantomastray** [comment]
I've verified normal mapping (w/o []) works fine as expected.
You can add in more mapper configs, to verify any more corner cases.

**Comment by pratyay-banerjee** [comment]
Just check for this one. The array containing n-level nested objects. This should do.
```
{
            "destinationNamespace":"or_test",
            "destinationEntity":"PersonGenericMapped",
            "columnMap": {
                "id":"id",
                "firstName":"nameArray[].name.firstname",
                "lastName":"nameArray[].name.lastname",
                "birthDate":"date.birth",
                "deleted":"deleted",
                "source_event_date" : "date.source[].event.date",
                "birthDate":"date.source[].event.birthdate"
            },
            "groupNo":"1"
        }]
```

**Pull request merged**
